### ISSUE TITLE
'jsxDEV' is not exported from 'react/jsx-dev-runtime' 

### ISSUE THREAD

**Issue by justindjeumenet** [hiroppy/nextjs-app-router-training#28]
Whenever you have time, please check this error. I am using WebStorm and cannot run the application normally. I am having this error below on multiple pages:

./src/app/global-error.tsx
./src/app/examples/template.tsx
Attempted import error: 'jsxDEV' is not exported from 'react/jsx-dev-runtime' (imported as '_jsxDEV').

Also the package hogan.js: 3.0.2 is using the deprecated mkdirp:0.3.0 and I updated the mkdirp package to 3.0.2 by adding this on package.json and running npm install.

  "resolutions": {
    "mkdirp": "3.0.1"
  },

Thank you for your help.

**Comment by hiroppy** [comment]
@justindjeumenet thank you for reporting, I think this issue is from Next.js, maybe this...? https://github.com/vercel/next.js/issues/61053

**Comment by justindjeumenet** [comment]
@hiroppy you are absolutely right. I just changed to next: 14.0.4 and everything is works great. Thanks again and great work.
#28
